---
- name: Install borg1 server
  hosts: all
  become: true
  tasks:
    - name: Set timezone
      become: yes
      timezone:
        name: Europe/Amsterdam
  roles:
    - role: postfix
      postfix_aliases:
      - user: root
        alias: tharre3@gmail.com
    - role: dotfiles
      tags: "dotfiles"

- include: debian.yml
- include: ts3server.yml
  tags: "ts3"
- include: gitolite.yml
  tags: "git"
- include: webserver.yml
  tags: "www"
